#!/usr/bin/env bun

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { DEFAULT_ASSETS_MANAGER } from "@gi-tcg/assets-manager";
import getData from "@gi-tcg/data";
import {
  CURRENT_VERSION,
  IllusionRealmTrainer,
  type ActionWeightsTrainingConfig,
  type RpcActionHeuristicWeights,
} from "../src/index";

const DEFAULT_DECK_1 =
  "FZDByRUNGRCB0WoNFlGgWpEPE0AB9TAPFGCB9kgWGIERCoEQDLFADcQQDPFgacYWDJAA";
const DEFAULT_DECK_2 =
  "FdHxNj8TAWDQxFkMFkAhyWIYCYDA45wOCUDQ5J0PGEAh9IIPGWDh9p4YC6FgirYRCxAA";

function parseArg(name: string): string | undefined {
  const prefix = `--${name}=`;
  const hit = process.argv.find((arg) => arg.startsWith(prefix));
  return hit ? hit.slice(prefix.length) : undefined;
}

function parseNumberArg(name: string, fallback: number): number {
  const raw = parseArg(name);
  if (!raw) {
    return fallback;
  }
  const value = Number(raw);
  return Number.isFinite(value) ? value : fallback;
}

function toNumber(value: number): number {
  return Number.isFinite(value) ? Number(value.toFixed(6)) : value;
}

function serializeWeights(weights: RpcActionHeuristicWeights): RpcActionHeuristicWeights {
  return {
    playCard: toNumber(weights.playCard),
    useSkill: toNumber(weights.useSkill),
    switchActive: toNumber(weights.switchActive),
    elementalTuning: toNumber(weights.elementalTuning),
    declareEnd: toNumber(weights.declareEnd),
    invalidAction: toNumber(weights.invalidAction),
    fastActionBonus: toNumber(weights.fastActionBonus),
    diceCostPenalty: toNumber(weights.diceCostPenalty),
  };
}

async function main() {
  const iterations = parseNumberArg("iterations", 8);
  const populationSize = parseNumberArg("population", 12);
  const eliteSize = parseNumberArg("elites", 4);
  const battlesPerCandidate = parseNumberArg("battles", 2);
  const deckCode1 = parseArg("deck1") ?? DEFAULT_DECK_1;
  const deckCode2 = parseArg("deck2") ?? DEFAULT_DECK_2;

  const deck1 = DEFAULT_ASSETS_MANAGER.decode(deckCode1.trim());
  const deck2 = DEFAULT_ASSETS_MANAGER.decode(deckCode2.trim());
  const trainer = new IllusionRealmTrainer(getData(CURRENT_VERSION));

  const trainingConfig: ActionWeightsTrainingConfig = {
    deck1,
    deck2,
    iterations,
    populationSize,
    eliteSize,
    battlesPerCandidate,
    baseline: { mode: "heuristic" },
  };

  console.log("Training action heuristic weights...");
  console.log(
    `iterations=${iterations}, population=${populationSize}, elites=${eliteSize}, battles=${battlesPerCandidate}`,
  );

  const result = await trainer.trainActionWeights(trainingConfig);
  const trainedWeights = serializeWeights(result.bestWeights);
  const generatedAt = new Date().toISOString();
  const artifact = {
    generatedAt,
    version: CURRENT_VERSION,
    bestScore: toNumber(result.bestScore),
    config: {
      iterations,
      populationSize,
      eliteSize,
      battlesPerCandidate,
    },
    weights: trainedWeights,
    history: result.history.map((entry) => ({
      iteration: entry.iteration,
      bestScore: toNumber(entry.bestScore),
      averageScore: toNumber(entry.averageScore),
      bestWeights: serializeWeights(entry.bestWeights),
    })),
  };

  const outputTsPath = resolve(import.meta.dir, "../src/decoupled/trained_rpc_action_weights.ts");
  const outputJsonPath = resolve(
    import.meta.dir,
    "../src/decoupled/trained_rpc_action_weights.json",
  );
  const outputTs = `// Auto-generated by scripts/train_rpc_action_weights.ts\n// Do not edit manually.\n\nimport type { RpcActionHeuristicWeights } from "./heuristic_ai";\n\nexport const TRAINED_RPC_ACTION_HEURISTIC_WEIGHTS: RpcActionHeuristicWeights = ${JSON.stringify(trainedWeights, null, 2)};\n\nexport const TRAINED_RPC_ACTION_HEURISTIC_METADATA = {\n  generatedAt: "${generatedAt}",\n  source: "illusion_realm_trainer",\n  bestScore: ${toNumber(result.bestScore)},\n} as const;\n`;

  writeFileSync(outputTsPath, outputTs, "utf8");
  writeFileSync(outputJsonPath, `${JSON.stringify(artifact, null, 2)}\n`, "utf8");

  console.log(`Saved TS weights: ${outputTsPath}`);
  console.log(`Saved JSON artifact: ${outputJsonPath}`);
  console.log("Best weights:", trainedWeights);
  console.log(`Best score: ${toNumber(result.bestScore)}`);
}

await main();
