// Auto-generated by scripts/train_rpc_action_weights.ts
// Do not edit manually.

import type { RpcActionHeuristicWeights } from "./heuristic_ai";
// this is a example for implement a api to ai agent
export const TRAINED_RPC_ACTION_HEURISTIC_WEIGHTS: RpcActionHeuristicWeights = {
  "playCard": 120,
  "useSkill": 100,
  "switchActive": 60,
  "elementalTuning": 20,
  "declareEnd": -1000,
  "invalidAction": -500,
  "fastActionBonus": 10,
  "diceCostPenalty": 1
};

export const TRAINED_RPC_ACTION_HEURISTIC_METADATA = {
  generatedAt: "2026-02-28T02:57:10.331Z",
  source: "illusion_realm_trainer",
  bestScore: 0,
} as const;
